library("tidyverse")
library(dplyr)
library(tidyr)

# Load the CSV file
data <- read.csv("C:/Users/mise017/Downloads/FAO_excel_(6-30-25)_1-58PM (1).csv")

# Ensure the year column is numeric if it isn't already
data$Year.Code <- as.numeric(as.character(data$Year.Code))

# Define full year range
years_full <- 1961:2022

# Assume "area" and "item" are the correct grouping columns
# Adjust if the actual column names are different
expanded_data <- data %>%
  filter(!is.na(Value) & Value != 0) %>%
  distinct(Area, Item) %>%
  crossing(Year.Code = years_full) %>%
  left_join(data, by = c("Area", "Item", "Year.Code")) %>%
  arrange(Area, Item, Year.Code)

# Assign Item.Code..CPC. values based on item
expanded_data$Item.Code..CPC. <- case_when(
  expanded_data$Item == "Cattle (dairy)" ~ "F0960",
  expanded_data$Item == "Cattle (non-dairy)" ~ "F0961",
  expanded_data$Item == "Chickens (broilers)" ~ "F1053",
  expanded_data$Item == "Chickens (layers)" ~ "F1052",
  expanded_data$Item == "Ducks" ~ "02154",
  expanded_data$Item == "Goats" ~ "02123",
  expanded_data$Item == "Sheep" ~ "02122",
  expanded_data$Item == "Swine (breeding)" ~ "F1051",
  expanded_data$Item == "Swine (market)" ~ "F1049",
  expanded_data$Item == "Turkeys" ~ "02152",
  TRUE ~ expanded_data$Item.Code..CPC.  # keep existing if not matched
)
#fills in the correct area code (yes its sloppy)
expanded_data$Area.Code..M49. <- NA_character_
expanded_data$Area.Code..M49. <- case_when(
  expanded_data$Area == "Afghanistan" ~ "004",
  expanded_data$Area == "Albania" ~ "008",
  expanded_data$Area == "Algeria" ~ "012",
  expanded_data$Area == "Angola" ~ "024"
  expanded_data$Area == "Antigua and Barbuda" ~ "028",
  expanded_data$Area == "Argentina" ~ "032",
  expanded_data$Area == "Armenia" ~ "051",
  expanded_data$Area == "Australia" ~ "036",
  expanded_data$Area == "Austria" ~ "040",
  expanded_data$Area == "Azerbaijan" ~ "031",
  expanded_data$Area == "Bahamas" ~ "044",
  expanded_data$Area == "Bahrain" ~ "048",
  expanded_data$Area == "Bangladesh" ~ "050",
  expanded_data$Area == "Barbados" ~ "052",
  expanded_data$Area == "Belarus" ~ "112",
  expanded_data$Area == "Belgium-Luxembourg" ~ "058",
  expanded_data$Area == "Belgium" ~ "056",
  expanded_data$Area == "Belize" ~ "058",
  expanded_data$Area == "Benin" ~ "204",
  expanded_data$Area == "Bhutan" ~ "064",
  expanded_data$Area == "Bolivia (Plurinational State of)" ~ "068",
  expanded_data$Area == "Bosnia and Herzegovina" ~ "070",
  expanded_data$Area == "Botswana" ~ "072",
  expanded_data$Area == "Brazil" ~ "076",
  expanded_data$Area == "Brunei Darussalam" ~ "096",
  expanded_data$Area == "Bulgaria" ~ "100",
  expanded_data$Area == "Burkina Faso" ~ "854",
  expanded_data$Area == "Burundi" ~ "108",
  expanded_data$Area == "Cabo Verde" ~ "132",
  expanded_data$Area == "Cambodia" ~ "116",
  expanded_data$Area == "Cameroon" ~ "120",
  expanded_data$Area == "Canada" ~ "124",
  expanded_data$Area == "Central African Republic" ~ "140",
  expanded_data$Area == "Chad" ~ "148",
  expanded_data$Area == "Chile" ~ "152",
  expanded_data$Area == "China, mainland" ~ "156",
  expanded_data$Area == "China, Taiwan Province of" ~ "158",
  expanded_data$Area == "Colombia" ~ "170",
  expanded_data$Area == "Comoros" ~ "174",
  expanded_data$Area == "Congo" ~ "178",
  expanded_data$Area == "Costa Rica" ~ "188",
  expanded_data$Area == "Côte d'Ivoire" ~ "384",
  expanded_data$Area == "Croatia" ~ "191",
  expanded_data$Area == "Cuba" ~ "192",
  expanded_data$Area == "Cyprus" ~ "196",
  expanded_data$Area == "Czechia" ~ "203",
  expanded_data$Area == "Czechoslovakia" ~ "200",
  expanded_data$Area == "Democratic People's Republic of Korea" ~ "408",
  expanded_data$Area == "Democratic Republic of the Congo" ~ "180",
  expanded_data$Area == "Denmark" ~ "208",
  expanded_data$Area == "Djibouti" ~ "262",
  expanded_data$Area == "Dominican Republic" ~ "214",
  expanded_data$Area == "Dominica" ~ "212",
  expanded_data$Area == "Ecuador" ~ "218",
  expanded_data$Area == "Egypt" ~ "818",
  expanded_data$Area == "El Salvador" ~ "222",
  expanded_data$Area == "Equatorial Guinea" ~ "226",
  expanded_data$Area == "Eritrea" ~ "232",
  expanded_data$Area == "Estonia" ~ "233",
  expanded_data$Area == "Eswatini" ~ "748",
  expanded_data$Area == "Ethiopia" ~ "231",
  expanded_data$Area == "Ethiopia PDR" ~ "230",
  expanded_data$Area == "Fiji" ~ "242",
  expanded_data$Area == "Finland" ~ "246",
  expanded_data$Area == "France" ~ "250",
  expanded_data$Area == "Gabon" ~ "266",
  expanded_data$Area == "Gambia" ~ "270",
  expanded_data$Area == "Georgia" ~ "268",
  expanded_data$Area == "Germany" ~ "276",
  expanded_data$Area == "Ghana" ~ "288",
  expanded_data$Area == "Greece" ~ "300",
  expanded_data$Area == "Grenada" ~ "308",
  expanded_data$Area == "Guatemala" ~ "320",
  expanded_data$Area == "Guinea" ~ "324",
  expanded_data$Area == "Guinea-Bissau" ~ "624",
  expanded_data$Area == "Guyana" ~ "328",
  expanded_data$Area == "Haiti" ~ "332",
  expanded_data$Area == "Honduras" ~ "340",
  expanded_data$Area == "Hungary" ~ "348",
  expanded_data$Area == "Iceland" ~ "352",
  expanded_data$Area == "India" ~ "356",
  expanded_data$Area == "Indonesia" ~ "360",
  expanded_data$Area == "Iran (Islamic Republic of)" ~ "364",
  expanded_data$Area == "Iraq" ~ "368",
  expanded_data$Area == "Ireland" ~ "372",
  expanded_data$Area == "Israel" ~ "376",
  expanded_data$Area == "Italy" ~ "380",
  expanded_data$Area == "Jamaica" ~ "388",
  expanded_data$Area == "Japan" ~ "392",
  expanded_data$Area == "Jordan" ~ "400",
  expanded_data$Area == "Kazakhstan" ~ "398",
  expanded_data$Area == "Kenya" ~ "404",
  expanded_data$Area == "Kiribati" ~ "296",
  expanded_data$Area == "Kuwait" ~ "414",
  expanded_data$Area == "Kyrgyzstan" ~ "417",
  expanded_data$Area == "Lao People's Democratic Republic" ~ "418",
  expanded_data$Area == "Latvia" ~ "428",
  expanded_data$Area == "Lebanon" ~ "422",
  expanded_data$Area == "Lesotho" ~ "426",
  expanded_data$Area == "Liberia" ~ "430",
  expanded_data$Area == "Libya" ~ "434",
  expanded_data$Area == "Liechtenstein" ~ "438",
  expanded_data$Area == "Lithuania" ~ "440",
  expanded_data$Area == "Luxembourg" ~ "442",
  expanded_data$Area == "Madagascar" ~ "450",
  expanded_data$Area == "Malawi" ~ "454",
  expanded_data$Area == "Malaysia" ~ "458",
  expanded_data$Area == "Maldives" ~ "462",
  expanded_data$Area == "Mali" ~ "466",
  expanded_data$Area == "Malta" ~ "470",
  expanded_data$Area == "Martinique" ~ "474",
  expanded_data$Area == "Mauritania" ~ "478",
  expanded_data$Area == "Mauritius" ~ "480",
  expanded_data$Area == "Mayotte" ~ "175",
  expanded_data$Area == "Micronesia (Federated States of)" ~ "583",
  expanded_data$Area == "Mexico" ~ "484",
  expanded_data$Area == "Mongolia" ~ "496",
  expanded_data$Area == "Montenegro" ~ "499",
  expanded_data$Area == "Montserrat" ~ "500",
  expanded_data$Area == "Morocco" ~ "504",
  expanded_data$Area == "Mozambique" ~ "508",
  expanded_data$Area == "Myanmar" ~ "104",
  expanded_data$Area == "Namibia" ~ "516",
  expanded_data$Area == "Nauru" ~ "520",
  expanded_data$Area == "Nepal" ~ "524",
  expanded_data$Area == "Netherlands (Kingdom of the)" ~ "528",
  expanded_data$Area == "New Caledonia" ~ "540",
  expanded_data$Area == "New Zealand" ~ "554",
  expanded_data$Area == "Nicaragua" ~ "558",
  expanded_data$Area == "Niger" ~ "562",
  expanded_data$Area == "Nigeria" ~ "566",
  expanded_data$Area == "Niue" ~ "570",
  expanded_data$Area == "North Macedonia" ~ "807",
  expanded_data$Area == "Norway" ~ "578",
  expanded_data$Area == "Oman" ~ "512",
  expanded_data$Area == "Pakistan" ~ "586",
  expanded_data$Area == "Palau" ~ "585",
  expanded_data$Area == "Palestine" ~ "275",
  expanded_data$Area == "Panama" ~ "591",
  expanded_data$Area == "Papua New Guinea" ~ "598",
  expanded_data$Area == "Paraguay" ~ "600",
  expanded_data$Area == "Peru" ~ "604",
  expanded_data$Area == "Philippines" ~ "608",
  expanded_data$Area == "Poland" ~ "616",
  expanded_data$Area == "Portugal" ~ "620",
  expanded_data$Area == "Puerto Rico" ~ "630",
  expanded_data$Area == "Qatar" ~ "634",
  expanded_data$Area == "Republic of Korea" ~ "410",
  expanded_data$Area == "Republic of Moldova" ~ "498",
  expanded_data$Area == "Romania" ~ "642",
  expanded_data$Area == "Russian Federation" ~ "643",
  expanded_data$Area == "Rwanda" ~ "646",
  expanded_data$Area == "Saint Kitts and Nevis" ~ "659",
  expanded_data$Area == "Saint Lucia" ~ "662",
  expanded_data$Area == "Saint Vincent and the Grenadines" ~ "670",
  expanded_data$Area == "Samoa" ~ "882",
  expanded_data$Area == "Sao Tome and Principe" ~ "678",
  expanded_data$Area == "Saudi Arabia" ~ "682",
  expanded_data$Area == "Senegal" ~ "686",
  expanded_data$Area == "Serbia" ~ "688",
  expanded_data$Area == "Serbia and Montenegro" ~ "690",
  expanded_data$Area == "Seychelles" ~ "690",
  expanded_data$Area == "Sierra Leone" ~ "694",
  expanded_data$Area == "Singapore" ~ "702",
  expanded_data$Area == "Slovakia" ~ "703",
  expanded_data$Area == "Slovenia" ~ "705",
  expanded_data$Area == "Solomon Islands" ~ "090",
  expanded_data$Area == "Somalia" ~ "706",
  expanded_data$Area == "South Africa" ~ "710",
  expanded_data$Area == "South Sudan" ~ "728",
  expanded_data$Area == "Spain" ~ "724",
  expanded_data$Area == "Sri Lanka" ~ "144",
  expanded_data$Area == "State of Palestine" ~ "275",
  expanded_data$Area == "Sudan" ~ "729",
  expanded_data$Area == "Sudan (former)" ~ "736",
  expanded_data$Area == "Suriname" ~ "740",
  expanded_data$Area == "Sweden" ~ "752",
  expanded_data$Area == "Switzerland" ~ "756",
  expanded_data$Area == "Syrian Arab Republic" ~ "760",
  expanded_data$Area == "Tajikistan" ~ "762",
  expanded_data$Area == "Thailand" ~ "764",
  expanded_data$Area == "Timor-Leste" ~ "626",
  expanded_data$Area == "Togo" ~ "768",
  expanded_data$Area == "Tonga" ~ "776",
  expanded_data$Area == "Trinidad and Tobago" ~ "780",
  expanded_data$Area == "Tunisia" ~ "788",
  expanded_data$Area == "Türkiye" ~ "792",
  expanded_data$Area == "Turkmenistan" ~ "795",
  expanded_data$Area == "Tuvalu" ~ "798",
  expanded_data$Area == "Uganda" ~ "800",
  expanded_data$Area == "Ukraine" ~ "804",
  expanded_data$Area == "United Arab Emirates" ~ "784",
  expanded_data$Area == "United Kingdom of Great Britain and Northern Ireland" ~ "826",
  expanded_data$Area == "United Republic of Tanzania" ~ "834",
  expanded_data$Area == "United States of America" ~ "840",
  expanded_data$Area == "Uruguay" ~ "858",
  expanded_data$Area == "USSR" ~ "810",
  expanded_data$Area == "Uzbekistan" ~ "860",
  expanded_data$Area == "Vanuatu" ~ "548",
  expanded_data$Area == "Venezuela (Bolivarian Republic of)" ~ "862",
  expanded_data$Area == "Viet Nam" ~ "704",
  expanded_data$Area == "Yemen" ~ "887",
  expanded_data$Area == "Yugoslav SFR" ~ "890",
  expanded_data$Area == "Zambia" ~ "894",
  expanded_data$Area == "Zimbabwe" ~ "716",


  #non-country territories



  expanded_data$Area == "American Samoa" ~ "016",
  expanded_data$Area == "Anguilla" ~ "660",
  expanded_data$Area == "Antarctica" ~ "010",
  expanded_data$Area == "Aruba" ~ "533",
  expanded_data$Area == "Bermuda" ~ "060",
  expanded_data$Area == "Bonaire, Sint Eustatius and Saba" ~ "535",
  expanded_data$Area == "British Virgin Islands" ~ "092",
  expanded_data$Area == "Cayman Islands" ~ "136",
  expanded_data$Area == "Christmas Island" ~ "162",
  expanded_data$Area == "Cocos (Keeling) Islands" ~ "166",
  expanded_data$Area == "Cook Islands" ~ "184",
  expanded_data$Area == "Curacao" ~ "531",
  expanded_data$Area == "Falkland Islands (Malvinas)" ~ "238",
  expanded_data$Area == "Faroe Islands" ~ "234",
  expanded_data$Area == "French Guiana" ~ "254",
  expanded_data$Area == "French Polynesia" ~ "258",
  expanded_data$Area == "French Southern Territories" ~ "260",
  expanded_data$Area == "Gibraltar" ~ "292",
  expanded_data$Area == "Greenland" ~ "304",
  expanded_data$Area == "Guadeloupe" ~ "312",
  expanded_data$Area == "Guam" ~ "316",
  expanded_data$Area == "Guernsey" ~ "831",
  expanded_data$Area == "China, Hong Kong SAR" ~ "344",
  expanded_data$Area == "Isle of Man" ~ "833",
  expanded_data$Area == "Jersey" ~ "832",
  expanded_data$Area == "China, Macau SAR" ~ "446",
  expanded_data$Area == "Martinique" ~ "474",
  expanded_data$Area == "Mayotte" ~ "175",
  expanded_data$Area == "Montserrat" ~ "500",
  expanded_data$Area == "New Caledonia" ~ "540",
  expanded_data$Area == "Niue" ~ "570",
  expanded_data$Area == "Norfolk Island" ~ "574",
  expanded_data$Area == "Northern Mariana Islands" ~ "580",
  expanded_data$Area == "Pitcairn" ~ "612",
  expanded_data$Area == "Puerto Rico" ~ "630",
  expanded_data$Area == "Réunion" ~ "638",
  expanded_data$Area == "Saint Barthelemy" ~ "652",
  expanded_data$Area == "Ascension, Saint Helena and Tristan da Cunha" ~ "654",
  expanded_data$Area == "Saint Martin (French part)" ~ "663",
  expanded_data$Area == "Saint Pierre and Miquelon" ~ "666",
  expanded_data$Area == "Sint Maarten (Dutch part)" ~ "534",
  expanded_data$Area == "South Georgia and the South Sandwich Islands" ~ "239",
  expanded_data$Area == "Tokelau" ~ "772",
  expanded_data$Area == "Turks and Caicos Islands" ~ "796",
  expanded_data$Area == "United States Virgin Islands" ~ "850",
  expanded_data$Area == "Wallis and Futuna Islands" ~ "876",
  expanded_data$Area == "Western Sahara" ~ "732",

)



# Write to a new CSV file
write.csv(expanded_data, "2nd_fao_data.csv", row.names = FALSE)

cat("Expanded data written to 2nd_fao_data.csv\n")
file.exists("2nd_fao_data.csv")
iteration_2 <- read_csv("2nd_fao_data.csv")
